<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Redirecting...</title>

    <!-- Meta Refresh Redirect -->
    <meta http-equiv="refresh" content="5; url=https://www.asomgk.in/" />
    
    <!-- Optional Styling -->
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>Redirecting to the new page...</h1>
    <p>If you are not redirected automatically, <a href="https://www.asomgk.in/">click here</a>.</p>
</body>
</html>
